theme: minima
title: yay blog
author: k01e
email: harrymcmanus10@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  it seems you have run into a random pages site
  do not worry
  there is literally nothing of importance here
  you running into this was probably an accident anyway
  :)

# social links
twitter_username: i-need-a-twiter-acount # DO NOT include the @ character, or else the build will fail!
github_username:  k01e-py # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
